% ECE2020_Project_1.m

% This matlab program plots the load active and reactive powers, 
% the active and reactive powers generated by the source, the 
% power lost in line and source combined, the magnitude of the 
% source current and the power factor of the source as the value 
% of the capacitor varies between 0𝑚𝐹 to 1.5𝑚𝐹. This program is
% based on the circuit provided for Project 1.

% Tate Finley, 2-23-23,
% Rev. 2-23-23


C = linspace(0, (1.5*10^-3), 1001); % capacitor between 0 and 1.5mF
Xc = 1./(C.*377);
Zc = -1j.*Xc; % capacitor impedance
Zt = ((2+2j).*Zc)./(2+2j+Zc); % total load impendance
Lp = atan(imag(Zt)./real(Zt)); % load phase
pf = cos(Lp); % power factor of load + capacitor

% First plot is solving for the power factor
figure(1);
plot(C, pf);
xlabel('Capacitance mF');
ylabel('Power Factor');
title('Power factor of load + capacitor vs Capacitance');

Ic = 120./Zc; % current of capacitor
Is = Ic + 30.31 - 30.31j; % current of source
Im = sqrt((real(Is).^2)+(imag(Is).^2)); % magnitude of source current

% Second plot is solving for the magnitude in Source Current
figure(2);
plot(C, Im);
xlabel('Capacitance mF');
ylabel('Magnitude of Source Current (A)');
title('Source Current vs Capacitance');

% Third plot for Active and Reactive power for combined load
Sld = 120.*conj(Is);%total load power
figure(3);
hold on;
plot(C, real(Sld)); 
plot(C, imag(Sld));
hold off;
xlabel('Capacitance mF');
ylabel('Power of load w/ capacitator');
title('Active and Reactive Powers of load vs Capacitance');
legend('Active (W)', 'Reactive (VAR)');

% Next plot for power lost in line and source combined
SLoss = (2+2j+Zc).*(Im.^2);% power lost
PLoss = real(SLoss); % active power lost
figure(4);
plot(C, PLoss);
xlabel('Capacitance mF');
ylabel('Power lost in line and source combined (W)');
title('Power lost vs Capacitance');

% Final Plot for active and reactive power generated by the source
Sc = 120.*conj(Ic);
SGen = SLoss + Sc + 3636.55 + 3636.55j;% power generated
figure(5);
hold on;
plot(C, real(SGen)); 
plot(C, imag(SGen));
hold off;
xlabel('Capacitance mF');
ylabel('Power Generated by Source');
title('Power Generated for Circuit');
legend('Active (W)', 'Reactive (VAR)');
